name: 自动同步上游代码

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 12 点自动运行一次
  workflow_dispatch: # 同时也支持你手动点击运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 同步上游代码
        uses: tgymnich/fork-sync@v1.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main      # 你自己的分支名（通常是 main）
          head: main      # 原作者的分支名（通常是 main）
          owner: shuaiplus # 原作者的用户名
